{
 "title": "Telegram Alarms",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Impfzentrum Liederhalle ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"70174#Stuttgart166153284Impfzentrum Klinikum Stuttgart in der Liederhalle (Hegel-Saal)\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Robert-Bosch-Krankenhau",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"70376#Stuttgart166153284Impfzentrum am Robert-Bosch-Krankenhaus\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Leinfelden-Echterdingen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"70629#Leinfelden-Echterdingen166153284KIZ Messe Stuttgart (Landkreis Esslingen)\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Böblingen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"71065#Sindelfingen 166153284KIZ Böblingen\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Mönsheim",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"71297#Mönsheim166153284KIZ Enzkreis - Appenbergsporthalle\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Waiblingen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"71334#Waiblingen166153284Kreisimpfzentrum Waiblingen\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Ludwigsburg",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"71636#Ludwigsburg166153284Impfzentrum Ludwigsburg\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Tübingen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"72072#Tübingen166153284Paul Horn Arena\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Calw",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"72213#Altensteig-Wart166153284KiZ Kreis Calw\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Freudenstadt",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"72280#Dornstetten166153284Kreisimpfzentrum Landkreis Freudenstadt\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Zollernalbkreis",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"72469#Meßstetten166153284Kreisimpfzentrum Zollernalbkreis\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  },
  {
   "title": "Impfzentrum Reutlingen",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "impfzentrum_status{zentrum=\"72762#Reutlingen166153284Stadion an der Kreuzeiche\"}",
     "legendFormat": "Impfstoff"
    }
   ]
  }
 ]
}